### ISSUE TITLE
Renga init with endpoint does not save it

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renga-python#57]
Scenario:
```bash
renga init --endpoint https://example.com --autosync
```
Then the following is not working:
```
renga contexts list
```

I can fix by changing `.renga/config.yml` from:
```yml
core:
  autosync: true
  generated: '2017-10-25T11:36:10.689296'
  name: MyProject
endpoints:
  https://example.com:
    vertex_id: '20688'
```
to
```yml
core:
  autosync: true
  generated: '2017-10-25T11:36:10.689296'
  name: MyProject
  default: https://example.com
endpoints:
  https://example.com:
    vertex_id: '20688'
```
but it would be nice to have it inferred from the init command.
